/**
 * @fileoverview Library entry point of the toolkit.
 */

import {base64Tool} from './tools/base64.js';
import {echoTool} from './tools/executor.js';
import {hashTool} from './tools/hash.js';
import {binaryTool, hexTool} from './tools/hex-binary.js';
import {jsonFormatTool} from './tools/json-format.js';
import {jsonQueryTool} from './tools/json-query.js';
import {regexTool} from './tools/regex.js';
import {semverTool} from './tools/semver.js';
import {csvTool} from './tools/csv.js';
import {timeTool} from './tools/time.js';
import {base64FileTool, hashFileTool, hexFileTool} from './tools/file.js';
import {jwtTool} from './tools/jwt.js';
import {morseTool, rot13Tool} from './tools/rot13-morse.js';
import {textStatsTool} from './tools/text-stats.js';
import {htmlTool, urlTool} from './tools/url-html.js';
import {uuidTool} from './tools/uuid.js';
import {
  webBatchTool,
  webFetchTool,
  webRequestTool,
  webResearchTool,
  webSearchTool,
  webSuggestTool,
  webSummaryTool,
  webVerifyTool,
} from './tools/web.js';
import type {ToolDefinition} from './types/tools.js';

export {createConfig, defaultConfig} from './core/config.js';
export {ToolkitError} from './core/errors.js';
export {createLogger, type Logger, type LogSink} from './core/logger.js';
export {
  DEFAULT_PROTOCOL_VERSION,
  SERVER_NAME,
  SUPPORTED_PROTOCOL_VERSIONS,
  createMcpServer,
  runMcpServer,
  type McpMessage,
  type McpResponse,
  type McpServer,
  type McpServerOptions,
} from './mcp.js';
export {
  BASE64_FILE_TOOL_NAME,
  BASE64_TOOL_NAME,
  BINARY_TOOL_NAME,
  CSV_TOOL_NAME,
  DEFAULT_HASH_ALGORITHM,
  DEFAULT_UUID_COUNT,
  HASH_FILE_TOOL_NAME,
  HEX_FILE_TOOL_NAME,
  HEX_TOOL_NAME,
  HTML_TOOL_NAME,
  JWT_TOOL_NAME,
  JSON_QUERY_TOOL_NAME,
  MAX_UUID_COUNT,
  MORSE_TOOL_NAME,
  REGEX_TOOL_NAME,
  ROT13_TOOL_NAME,
  SEMVER_TOOL_NAME,
  TIME_TOOL_NAME,
  URL_TOOL_NAME,
  UUID_TOOL_NAME,
  WEB_BATCH_TOOL_NAME,
  WEB_FETCH_TOOL_NAME,
  WEB_REQUEST_TOOL_NAME,
  WEB_RESEARCH_TOOL_NAME,
  WEB_SEARCH_TOOL_NAME,
  WEB_SUGGEST_TOOL_NAME,
  WEB_SUMMARY_TOOL_NAME,
  WEB_VERIFY_TOOL_NAME,
  base64FileTool,
  base64Tool,
  binaryTool,
  createRegistry,
  csvTool,
  echoTool,
  executeTool,
  failure,
  getTool,
  hashFileTool,
  hashTool,
  hexFileTool,
  hexTool,
  htmlTool,
  jsonFormatTool,
  jsonQueryTool,
  jwtTool,
  listTools,
  morseTool,
  regexTool,
  rot13Tool,
  semverTool,
  success,
  textStatsTool,
  timeTool,
  urlTool,
  uuidTool,
  webBatchTool,
  webFetchTool,
  webRequestTool,
  webResearchTool,
  webSearchTool,
  webSuggestTool,
  webSummaryTool,
  webVerifyTool,
  type ToolRegistry,
} from './tools/index.js';
export {
  base64Decode,
  base64Encode,
  binaryDecode,
  binaryEncode,
  center,
  computeTextStats,
  CRYPTO_HASH_ALGORITHMS,
  crawlDocumentation,
  crawlSitemap,
  codecFile,
  cryptoHash,
  decodeJwt,
  DEFAULT_CRAWL_DEPTH,
  DEFAULT_CRAWL_MAX_LENGTH,
  DEFAULT_DELIMITER,
  DEFAULT_FILE_MAX_LENGTH,
  DEFAULT_INDENT,
  DEFAULT_TIME_FORMAT,
  DEFAULT_TIME_LOCALE,
  DEFAULT_MAX_PAGES,
  DEFAULT_REGEX_MAX_LENGTH,
  DEFAULT_REQUEST_MAX_LENGTH,
  extractLinks,
  formatJson,
  generateUuid,
  HASH_ALGORITHMS,
  hashFile,
  hashText,
  hexDecode,
  hexEncode,
  htmlDecode,
  htmlEncode,
  htmlToMarkdown,
  isHashAlgorithm,
  MAX_CRAWL_DEPTH,
  MAX_CRAWL_PAGES,
  MAX_INDENT,
  MAX_UUID,
  MORSE_WORD_SEPARATOR,
  morseDecode,
  morseEncode,
  NIL_UUID,
  parseArgv,
  parseCsv,
  parsePath,
  parseRange,
  parseVersion,
  PROTON_HASH_ALGORITHMS,
  PROTON_HASH_SEED,
  protonHash,
  protonHash64,
  queryJson,
  quote,
  readFileBytes,
  readHtmlAttribute,
  REQUEST_METHODS,
  repeatChar,
  requestUrl,
  resolveFilePath,
  rot13,
  satisfiesRange,
  stringifyCsv,
  SUPPORTED_FLAGS,
  TAB_DELIMITER,
  addTime,
  describeTime,
  diffTime,
  formatTime,
  parseDuration,
  parseTime,
  truncate,
  urlDecode,
  urlEncode,
  validateUuid,
  applyRegex,
  bumpVersion,
  compareVersions,
  type HtmlToMarkdownOptions,
  type JsonFormatResult,
  type ParsedArgv,
  type RegexOptions,
  type SemverRelease,
} from './utils/index.js';
export type {
  CodecFileResult,
  CodecMode,
  ContentItem,
  CrawlError,
  CrawlOptions,
  CrawlPage,
  CrawlResult,
  CryptoHashAlgorithm,
  CsvMode,
  CsvResult,
  CsvTable,
  EncodingFormat,
  ExecuteOptions,
  FileEncoding,
  HashAlgorithm,
  HashFileResult,
  JsonFormatOptions,
  JsonObject,
  JsonPrimitive,
  JsonQueryMatch,
  JsonQueryResult,
  JsonSchema,
  JsonValue,
  JwtParts,
  LogLevel,
  ProtonHashAlgorithm,
  RegexMatch,
  RegexMode,
  RegexResult,
  RequestMethod,
  RequestOptions,
  RequestResult,
  SearchResult,
  SemVer,
  SemverAction,
  SemverResult,
  TextContent,
  TextStats,
  TimeAction,
  TimePoint,
  TimeResult,
  TimeSpan,
  ToolkitConfig,
  ToolContext,
  ToolDefinition,
  ToolHandler,
  ToolInfo,
  ToolOutput,
  UuidString,
  UuidValidation,
  UuidVersion,
} from './types/index.js';

/**
 * @brief Built-in tools shipped with the toolkit.
 *
 * @return A fresh list of tool definitions.
 */
export function defaultTools(): ToolDefinition[] {
  return [
    echoTool(),
    textStatsTool(),
    jsonFormatTool(),
    jsonQueryTool(),
    regexTool(),
    semverTool(),
    csvTool(),
    timeTool(),
    hashTool(),
    hashFileTool(),
    base64Tool(),
    base64FileTool(),
    hexTool(),
    hexFileTool(),
    binaryTool(),
    urlTool(),
    htmlTool(),
    rot13Tool(),
    morseTool(),
    jwtTool(),
    uuidTool(),
    webSearchTool(),
    webFetchTool(),
    webRequestTool(),
    webSuggestTool(),
    webSummaryTool(),
    webBatchTool(),
    webVerifyTool(),
    webResearchTool(),
  ];
}
