/**
 * @fileoverview Library entry point of the toolkit.
 */

import {base64Tool} from './tools/base64.js';
import {echoTool} from './tools/executor.js';
import {hashTool} from './tools/hash.js';
import {binaryTool, hexTool} from './tools/hex-binary.js';
import {jsonFormatTool} from './tools/json-format.js';
import {jwtTool} from './tools/jwt.js';
import {morseTool, rot13Tool} from './tools/rot13-morse.js';
import {textStatsTool} from './tools/text-stats.js';
import {htmlTool, urlTool} from './tools/url-html.js';
import {uuidTool} from './tools/uuid.js';
import {
  webBatchTool,
  webFetchTool,
  webResearchTool,
  webSearchTool,
  webSuggestTool,
  webSummaryTool,
  webVerifyTool,
} from './tools/web.js';
import type {ToolDefinition} from './types/tools.js';

export {createConfig, defaultConfig} from './core/config.js';
export {ToolkitError} from './core/errors.js';
export {createLogger, type Logger, type LogSink} from './core/logger.js';
export {
  DEFAULT_PROTOCOL_VERSION,
  SERVER_NAME,
  SUPPORTED_PROTOCOL_VERSIONS,
  createMcpServer,
  runMcpServer,
  type McpMessage,
  type McpResponse,
  type McpServer,
  type McpServerOptions,
} from './mcp.js';
export {
  BASE64_TOOL_NAME,
  BINARY_TOOL_NAME,
  DEFAULT_HASH_ALGORITHM,
  DEFAULT_UUID_COUNT,
  HEX_TOOL_NAME,
  HTML_TOOL_NAME,
  JWT_TOOL_NAME,
  MAX_UUID_COUNT,
  MORSE_TOOL_NAME,
  ROT13_TOOL_NAME,
  URL_TOOL_NAME,
  UUID_TOOL_NAME,
  WEB_BATCH_TOOL_NAME,
  WEB_FETCH_TOOL_NAME,
  WEB_RESEARCH_TOOL_NAME,
  WEB_SEARCH_TOOL_NAME,
  WEB_SUGGEST_TOOL_NAME,
  WEB_SUMMARY_TOOL_NAME,
  WEB_VERIFY_TOOL_NAME,
  base64Tool,
  binaryTool,
  createRegistry,
  echoTool,
  executeTool,
  failure,
  getTool,
  hashTool,
  hexTool,
  htmlTool,
  jsonFormatTool,
  jwtTool,
  listTools,
  morseTool,
  rot13Tool,
  success,
  textStatsTool,
  urlTool,
  uuidTool,
  webBatchTool,
  webFetchTool,
  webResearchTool,
  webSearchTool,
  webSuggestTool,
  webSummaryTool,
  webVerifyTool,
  type ToolRegistry,
} from './tools/index.js';
export {
  base64Decode,
  base64Encode,
  binaryDecode,
  binaryEncode,
  center,
  computeTextStats,
  CRYPTO_HASH_ALGORITHMS,
  crawlDocumentation,
  crawlSitemap,
  cryptoHash,
  decodeJwt,
  DEFAULT_CRAWL_DEPTH,
  DEFAULT_CRAWL_MAX_LENGTH,
  DEFAULT_INDENT,
  DEFAULT_MAX_PAGES,
  extractLinks,
  formatJson,
  generateUuid,
  HASH_ALGORITHMS,
  hashText,
  hexDecode,
  hexEncode,
  htmlDecode,
  htmlEncode,
  htmlToMarkdown,
  isHashAlgorithm,
  MAX_CRAWL_DEPTH,
  MAX_CRAWL_PAGES,
  MAX_INDENT,
  MAX_UUID,
  MORSE_WORD_SEPARATOR,
  morseDecode,
  morseEncode,
  NIL_UUID,
  parseArgv,
  PROTON_HASH_ALGORITHMS,
  PROTON_HASH_SEED,
  protonHash,
  protonHash64,
  quote,
  readHtmlAttribute,
  repeatChar,
  rot13,
  truncate,
  urlDecode,
  urlEncode,
  validateUuid,
  type HtmlToMarkdownOptions,
  type JsonFormatResult,
  type ParsedArgv,
} from './utils/index.js';
export type {
  CodecMode,
  ContentItem,
  CrawlError,
  CrawlOptions,
  CrawlPage,
  CrawlResult,
  CryptoHashAlgorithm,
  EncodingFormat,
  ExecuteOptions,
  HashAlgorithm,
  JsonFormatOptions,
  JsonObject,
  JsonPrimitive,
  JsonSchema,
  JsonValue,
  JwtParts,
  LogLevel,
  ProtonHashAlgorithm,
  SearchResult,
  TextContent,
  TextStats,
  ToolkitConfig,
  ToolContext,
  ToolDefinition,
  ToolHandler,
  ToolInfo,
  ToolOutput,
  UuidString,
  UuidValidation,
  UuidVersion,
} from './types/index.js';

/**
 * @brief Built-in tools shipped with the toolkit.
 *
 * @return A fresh list of tool definitions.
 */
export function defaultTools(): ToolDefinition[] {
  return [
    echoTool(),
    textStatsTool(),
    jsonFormatTool(),
    hashTool(),
    base64Tool(),
    hexTool(),
    binaryTool(),
    urlTool(),
    htmlTool(),
    rot13Tool(),
    morseTool(),
    jwtTool(),
    uuidTool(),
    webSearchTool(),
    webFetchTool(),
    webSuggestTool(),
    webSummaryTool(),
    webBatchTool(),
    webVerifyTool(),
    webResearchTool(),
  ];
}
